import { lstat, readFile } from "node:fs/promises";
import { parseAllDocuments } from "yaml";
import { isAbsolute, relative, resolve } from "node:path";
import { matchesGlobWithDots } from "./glob.js";
import {
  DEFAULT_VERIFICATION_POLICY_SETTINGS,
  VERIFICATION_POLICY_SETTINGS_KEY,
  readVerificationPolicySettings,
  type PolicyCommand,
  type VerificationPolicySettings,
} from "../../shared/dist/verification-policy-settings.js";
import type { SettingsReader } from "./owner-language";
import { WHOLE_RUN_FILE } from "./test-runs.js";

/** What the Manager asked Core to check for one Task (tasks.verification_spec_json). */
export interface TaskVerificationSpec {
  readonly required_sections?: readonly string[];
  readonly required_tests?: readonly string[];
}

export type PolicyErrorKey =
  | "verification_no_output"
  | "verification_claimed_change_missing"
  | "verification_limit_exceeded"
  | "doc_empty"
  | "doc_section_missing"
  | "config_parse_failed"
  | "config_unsupported_format"
  | "test_failed"
  | "test_not_executed"
  | "test_required_not_executed"
  | "code_check_failed"
  | "code_unchecked"
  | "verification_spec_unreadable";

export interface PolicyCheck {
  command_id: string;
  passed: boolean;
  file?: string;
  argv?: string[];
  exit_code?: number | null;
  timed_out?: boolean;
  detail: string;
  stdout?: string;
  stderr?: string;
  /** Set on a failed check: what a Worker fix round is told went wrong. */
  error_key?: PolicyErrorKey;
}

export interface TypePolicyResult {
  policy: string;
  passed: boolean;
  core_checks: "executed" | "none_applicable";
  checks: PolicyCheck[];
  error_key: PolicyErrorKey | null;
  error: string | null;
}

export interface CommandOutcome {
  passed: boolean;
  exit_code?: number | null;
  timed_out?: boolean;
  stdout?: string;
  stderr?: string;
  error?: string;
}

export interface TypePolicyInput {
  type: string;
  /** Task worktree (absolute); null when the Task has none. */
  root: string | null;
  /** Files this Task changed, relative to root. */
  files: readonly string[];
  /** Tracked files this Task deleted, relative to root; a deletion is output even though nothing is left to check. */
  deletedFiles?: readonly string[];
  /** Tests Core removed because the Task had no spec_test criterion; their removal remains Task output when no other change remains. */
  removedTests?: readonly string[];
  /** The Worker report's `changes[]` entries. */
  claimedChanges: ReadonlyArray<{ file: string; action: string }>;
  spec: TaskVerificationSpec;
  settings: VerificationPolicySettings;
  /** "sole": no Project plan, so these checks are the only ones. "supplement": the Project plan decides; only static checks and test runs are added. */
  mode: "sole" | "supplement";
  runCommand: (argv: string[], cwd: string) => Promise<CommandOutcome>;
  /** Files Core's own test run already judged; those are not started again and carry no output. */
  coreTestRun?: { run_id: string | null; mode?: "full" | "selected"; passed_files: readonly string[]; failed_files: readonly string[] };
}

const DELETE_ACTIONS = new Set(["delete", "deleted", "remove", "removed"]);

/** Generated by package managers; CI's --frozen-lockfile judges them, so config checks never apply (extra patterns go in config.skip_patterns). */
const LOCKFILE_PATTERNS: readonly string[] = [
  "**/pnpm-lock.yaml", "**/package-lock.json", "**/npm-shrinkwrap.json", "**/yarn.lock", "**/bun.lock", "**/bun.lockb",
  "**/Cargo.lock", "**/poetry.lock", "**/uv.lock", "**/Pipfile.lock", "**/Gemfile.lock", "**/go.sum", "**/composer.lock",
  "**/mix.lock", "**/pubspec.lock", "**/Podfile.lock", "**/flake.lock",
];

const matchesAny = (file: string, patterns: readonly string[]): boolean => patterns.some((pattern) => matchesGlobWithDots(file, pattern));
const firstRunner = (file: string, runners: readonly PolicyCommand[]): PolicyCommand | undefined => runners.find((runner) => matchesGlobWithDots(file, runner.pattern));
const expand = (argv: readonly string[], file: string): string[] => argv.map((part) => part.replaceAll("{file}", file));

function insideRoot(root: string, file: string): string | null {
  if (file.length === 0 || isAbsolute(file)) return null;
  const absolute = resolve(root, file);
  const rel = relative(root, absolute);
  return rel === "" || rel.startsWith("..") ? null : absolute;
}

async function readText(path: string, maxBytes: number): Promise<string | null> {
  const info = await lstat(path).catch(() => null);
  if (!info?.isFile() || info.size > maxBytes) return null;
  return readFile(path, "utf8").catch(() => null);
}

/** The stored policy settings; missing or invalid values fall back to the defaults. A failed read never blocks verification. */
export function verificationPolicySettings(reader: SettingsReader): VerificationPolicySettings {
  try {
    const row = reader.get<{ value_json: string }>("SELECT value_json FROM settings WHERE key = ?", VERIFICATION_POLICY_SETTINGS_KEY);
    if (!row) return DEFAULT_VERIFICATION_POLICY_SETTINGS;
    return readVerificationPolicySettings(JSON.parse(row.value_json) as unknown, (message) => {
      console.warn(`[owl-core] ${message}`);
    });
  } catch (error) {
    console.warn("[owl-core] Could not read the verification policy; using defaults.", error);
    return DEFAULT_VERIFICATION_POLICY_SETTINGS;
  }
}

/**
 * Judge a Task's output by its type, independently of the Worker's own claim.
 * The rules (patterns, commands, limits) come from `settings`; nothing here names an extension.
 */
export async function evaluateTaskTypePolicy(input: TypePolicyInput): Promise<TypePolicyResult> {
  const { settings, spec, mode, runCommand } = input;
  const { limits } = settings;
  const root = input.root ?? "";
  const checks: PolicyCheck[] = [];
  const result: TypePolicyResult = { policy: input.type, passed: true, core_checks: "none_applicable", checks, error_key: null, error: null };
  const record = (check: PolicyCheck, key?: PolicyErrorKey): boolean => {
    checks.push(key ? { ...check, passed: false, error_key: key } : { ...check, passed: true });
    result.core_checks = "executed";
    if (key) {
      result.passed = false;
      result.error_key ??= key;
      result.error ??= check.detail;
    }
    return key === undefined;
  };
  /** Required checks that could not be run fail the Task: only Core's own checks may pass a Task without a Project. */
  const unchecked = (key: PolicyErrorKey, reason: string): void => {
    if (mode === "sole" && result.passed) record({ command_id: `policy:${key}`, passed: false, detail: reason }, key);
  };
  const limited = (files: readonly string[]): string[] => {
    if (files.length > limits.max_files_per_check) unchecked("verification_limit_exceeded", `${files.length} files changed, more than the ${limits.max_files_per_check} that can be checked.`);
    return files.slice(0, limits.max_files_per_check);
  };
  const run = async (id: string, command: PolicyCommand, file: string, key: PolicyErrorKey): Promise<{ ok: boolean; stdout: string }> => {
    const argv = expand(command.argv, file);
    const core = id === "policy:test" ? input.coreTestRun : undefined;
    if (core?.passed_files.includes(file) || core?.failed_files.includes(file)) {
      const ok = core.passed_files.includes(file);
      const detail = `Core test run ${core.run_id ?? ""}`.trimEnd();
      return { ok: record({ command_id: id, passed: ok, file, detail }, ok ? undefined : key), stdout: "" };
    }
    const outcome = await runCommand(argv, root);
    const detail = outcome.passed
      ? `${argv.join(" ")} passed.`
      : `${argv.join(" ")} ${outcome.timed_out ? "timed out" : outcome.error ?? `exited with code ${outcome.exit_code ?? "unknown"}`}${outcome.stderr?.trim() ? `: ${outcome.stderr.trim().slice(-500)}` : ""}`;
    const ok = record({ command_id: id, passed: outcome.passed, file, argv, exit_code: outcome.exit_code ?? null, timed_out: outcome.timed_out === true, detail, stdout: outcome.stdout, stderr: outcome.stderr }, outcome.passed ? undefined : key);
    return { ok, stdout: outcome.stdout ?? "" };
  };

  if (input.type === "design") return result;
  if (input.root === null) {
    // No execution root was recorded for the Task: nothing can be inspected, so a required check cannot pass.
    if (["code", "doc", "config", "test"].includes(input.type)) {
      record({ command_id: "policy:worktree", passed: false, detail: "The Task has no worktree, so its output cannot be verified." }, "verification_no_output");
    }
    return result;
  }

  // Every claimed change must exist: a Worker that says it wrote a file it did not write is caught here.
  const deleted = new Set(input.deletedFiles ?? []);
  for (const change of input.claimedChanges) {
    if (DELETE_ACTIONS.has(change.action.toLowerCase()) || deleted.has(change.file)) continue;
    const absolute = insideRoot(root, change.file);
    const exists = absolute !== null && (await lstat(absolute).catch(() => null)) !== null;
    if (!exists) record({ command_id: "policy:claimed_changes", passed: false, file: change.file, detail: `The report lists ${change.file} as changed, but it is not in the Task worktree.` }, "verification_claimed_change_missing");
  }
  const types = ["code", "doc", "config", "test"];
  if (!types.includes(input.type)) return result;
  if (input.files.length === 0 && deleted.size > 0) {
    record({ command_id: "policy:output", passed: true, detail: `The Task deleted ${deleted.size} file(s) and changed nothing else, so nothing is left to check.` });
    return result;
  }
  if (input.files.length === 0 && (input.removedTests?.length ?? 0) > 0) {
    record({ command_id: "policy:output", passed: true, detail: `Core removed ${input.removedTests?.length} unrequested test file(s), so no other output remains to check.` });
    return result;
  }
  if (input.files.length === 0) {
    record({ command_id: "policy:output", passed: false, detail: "The Task changed no files, so there is nothing to verify." }, "verification_no_output");
    return result;
  }

  const read = (file: string): Promise<string | null> => {
    const absolute = insideRoot(root, file);
    return absolute === null ? Promise.resolve(null) : readText(absolute, limits.max_read_bytes);
  };

  if (input.type === "doc") {
    const docs = limited(input.files.filter((file) => matchesAny(file, settings.doc.file_patterns)));
    if (docs.length === 0) {
      record({ command_id: "policy:doc_content", passed: false, detail: "No changed file matches a document pattern." }, "doc_empty");
      return result;
    }
    const heading = new RegExp(settings.doc.heading_pattern);
    const fold = (text: string): string => (settings.doc.section_match === "folded" ? text.normalize("NFKC").trim().toLowerCase() : text.trim());
    const headings = new Set<string>();
    for (const file of docs) {
      const text = await read(file);
      if (text === null || text.trim().length === 0) {
        record({ command_id: "policy:doc_content", passed: false, file, detail: `${file} is missing, unreadable within the size limit, or empty.` }, "doc_empty");
        continue;
      }
      record({ command_id: "policy:doc_content", passed: true, file, detail: `${file} has content.` });
      for (const line of text.split("\n")) {
        const name = heading.exec(line)?.[1];
        if (name !== undefined) headings.add(fold(name));
      }
    }
    for (const section of new Set([...settings.doc.required_sections, ...(spec.required_sections ?? [])])) {
      if (headings.has(fold(section))) record({ command_id: "policy:doc_sections", passed: true, detail: `Section "${section}" is present.` });
      else record({ command_id: "policy:doc_sections", passed: false, detail: `The required section "${section}" is not a heading in the changed documents.` }, "doc_section_missing");
    }
    return result;
  }

  if (input.type === "config") {
    const lockfiles = input.files.filter((file) => matchesAny(file, LOCKFILE_PATTERNS));
    if (lockfiles.length > 0 && lockfiles.length === input.files.length) {
      record({ command_id: "policy:config_lockfile", passed: true, detail: `Only lockfiles changed (${lockfiles.join(", ")}); they are left to the frozen-lockfile check.` });
      return result;
    }
    const candidates = limited(input.files.filter((file) => !matchesAny(file, LOCKFILE_PATTERNS) && !matchesAny(file, settings.config.skip_patterns)));
    if (candidates.length === 0) unchecked("config_unsupported_format", "Every changed file is excluded from config checks, so nothing was verified.");
    const unsupported: string[] = [];
    for (const file of candidates) {
      const checker = firstRunner(file, settings.config.checkers);
      if (checker) {
        await run("policy:config_checker", checker, file, "config_parse_failed");
      } else if (matchesAny(file, settings.config.json_patterns)) {
        const text = await read(file);
        try {
          if (text === null) throw new Error("the file could not be read within the size limit");
          JSON.parse(text);
          record({ command_id: "policy:config_json", passed: true, file, detail: `${file} parses as JSON.` });
        } catch (error) {
          record({ command_id: "policy:config_json", passed: false, file, detail: `${file} is not valid JSON: ${error instanceof Error ? error.message : String(error)}` }, "config_parse_failed");
        }
      } else if (matchesAny(file, settings.config.yaml_patterns)) {
        const text = await read(file);
        try {
          if (text === null) throw new Error("the file could not be read within the size limit");
          const errors = parseAllDocuments(text).flatMap((document) => document.errors);
          if (errors.length > 0) throw errors[0];
          record({ command_id: "policy:config_yaml", passed: true, file, detail: `${file} parses as YAML.` });
        } catch (error) {
          record({ command_id: "policy:config_yaml", passed: false, file, detail: `${file} is not valid YAML: ${error instanceof Error ? error.message : String(error)}` }, "config_parse_failed");
        }
      } else unsupported.push(file);
    }
    if (unsupported.length > 0) unchecked("config_unsupported_format", `No parser or checker is configured for: ${unsupported.join(", ")}.`);
    return result;
  }

  const runTests = async (files: readonly string[]): Promise<{ executed: string[] }> => {
    const executed: string[] = [];
    for (const file of limited(files)) {
      const runner = firstRunner(file, settings.test.runners);
      if (!runner) continue;
      const outcome = await run("policy:test", runner, file, "test_failed");
      if (outcome.ok) executed.push(file);
    }
    return { executed };
  };

  if (input.type === "test") {
    const named: string[] = [];
    for (const name of spec.required_tests ?? []) {
      const absolute = insideRoot(root, name);
      if (absolute !== null && firstRunner(name, settings.test.runners) && (await lstat(absolute).catch(() => null))?.isFile()) named.push(name);
    }
    const { executed } = await runTests([...new Set([...input.files, ...named])]);
    for (const required of spec.required_tests ?? []) {
      if (executed.includes(required)) record({ command_id: "policy:required_tests", passed: true, detail: `Required test "${required}" ran and passed.` });
      else if (result.passed) record({ command_id: "policy:required_tests", passed: false, detail: `The required test "${required}" was not run by a passing test runner.` }, "test_required_not_executed");
    }
    if (checks.every((check) => check.command_id !== "policy:test")) unchecked("test_not_executed", "No changed file matches a configured test runner.");
    return result;
  }

  // code
  if (mode === "supplement") return result;
  let executed = 0;
  for (const file of limited(input.files)) {
    const checker = firstRunner(file, settings.code.checkers);
    if (!checker) continue;
    executed += 1;
    await run("policy:code_check", checker, file, "code_check_failed");
  }
  if (settings.code.run_test_runners) {
    const tests = await runTests(input.files.filter((file) => firstRunner(file, settings.test.runners)));
    executed += tests.executed.length;
  }
  // Why not add .ts to the global code.checkers/test.runners defaults: `node --check` cannot check it and the
  // defaults cannot vary per project. The Project's resolved test settings decide instead: a whole-command run
  // covers every changed file, so its result counts as the verification of this code Task. A per-file Project has
  // no whole command; there Core's selected run of the tests related to the changed files is the verification, and
  // it counts only when at least one test ran and none failed (failed files are judged by Core's own test gate).
  const core = input.coreTestRun;
  if (core && (core.passed_files.includes(WHOLE_RUN_FILE) || core.failed_files.includes(WHOLE_RUN_FILE))) {
    const ok = core.passed_files.includes(WHOLE_RUN_FILE);
    record({ command_id: "policy:test", passed: ok, file: WHOLE_RUN_FILE, detail: `Core whole test run ${core.run_id ?? ""}`.trimEnd() }, ok ? undefined : "test_failed");
    executed += 1;
  } else if (core?.mode === "selected" && core.passed_files.length > 0 && core.failed_files.length === 0) {
    record({ command_id: "policy:test", passed: true, detail: `Core selected test run${core.run_id ? ` ${core.run_id}` : ""} passed ${core.passed_files.length} related test file(s).` });
    executed += 1;
  }
  if (executed === 0 && result.passed) unchecked("code_unchecked", "No changed file matches a configured code checker or test runner.");
  return result;
}
